version: '3.3'

services:
  postgres:
    image: postgres:13-alpine
    volumes:
        - postgres_data:/var/lib/postgresql/data/
    environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_DB: ${DB_NAME}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
        - 5432:5432

  app:
    build: ./logic_server
    volumes:
        - ./logic_server:/workspace/
    command: python start.py
    # tty: true
    ports:
        - 8000:8000

  nginx-rtmp:
    build: ./streaming_server
    ports:
      - 1935:1935
      - 8080:80
      - 8443:443
    environment:
      - HTTP_PORT=80
      - RTMP_PORT=1935
    # volumes:
    #   - ./certs:/opt/certs  

      
volumes:
    postgres_data: