version: '3.3'

services:

    postgres:
        image: postgres:12-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - 5432:5432

    app:
        build: .
        volumes:
            - ./:/workspace/
        # command: uvicorn app.api.server:app --reload --workers 1 --host 0.0.0.0 --port 8000
        tty: true
        ports:
            - 8000:8000
      
volumes:
    postgres_data: